apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deegbo/argocd-self-managed.git
    targetRevision: main
    path: apps/                 # Folder where child Applications live
    directory:
      recurse: true             # Apply all YAMLs inside recursively
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
